# Meta Data for SEO

# Search
mainSections = ["ml", "etc", "docs"]

## Homepage
title = "Anurag Dhadse"
homeurl = ""
titleSeparator = "â€”"
titleAddition = "Wiki"
description = "My personal wiki!"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["wiki.png"]
ogLocale = "en_US"
domainTLD = "wiki.anuragdhadse.com"
titleHome = "Wiki"

## Twitter Cards
twitterSite = "@adhadse_"
twitterCreator = "@adhadse_"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Wiki"
schemaAuthor = "Anurag Dhadse"
schemaAuthorTwitter = "https://twitter.com/adhadse"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/adhadse/"
schemaAuthorGitHub = "https://github.com/adhadse"
schemaLocale = "en-US"
schemaLogo = "logo-wiki.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "wiki.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/adhadse_"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/adhadse/wiki"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022, Anurag Dhadse"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/adhadse/wiki"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = true
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true


